# Pencereyi ikiye böl
split-window -h
# Sağ tarafta fastfetch çalıştır
select-pane -t 1
send-keys "fastfetch" Enter
# Sol tarafta görsel scriptini çalıştır
select-pane -t 0
send-keys "~/.config/zsh/show_random_image.sh" Enter