-- Generated by wallust — Hyprland colors

hl.config({
    general = {
        col = {
            active_border   = {
                colors = {
                    "rgb({{color4 | strip}})",
                    "rgb({{color6 | strip}})",
                },
                angle = 45
            },
            inactive_border = "rgb({{color8 | strip}})",
        },
    },
    decoration = {
        shadow = {
            color = 0xee{{color0 | strip}},
        },
    },
})
