#!/bin/bash
# Generated by wallust — Zsh/Terminal color variables

export MATUGEN_PRIMARY="{{color4}}"
export MATUGEN_ON_PRIMARY="{{background}}"
export MATUGEN_SECONDARY="{{color5}}"
export MATUGEN_TERTIARY="{{color6}}"
export MATUGEN_SURFACE="{{background}}"
export MATUGEN_ON_SURFACE="{{foreground}}"
export MATUGEN_OUTLINE="{{color8}}"
export MATUGEN_ERROR="{{color1}}"
export MATUGEN_PRIMARY_CONTAINER="{{color12}}"
export MATUGEN_SURFACE_CONTAINER="{{color0}}"

export MATUGEN_ZSH_AUTOSUGGEST="{{color8}}"
export MATUGEN_ZSH_NUMBER="{{color3}}"
export MATUGEN_ZSH_OPTION="{{color2}}"
export MATUGEN_ZSH_BRACKET="{{color6}}"
