#!/bin/bash
# Generated by matugen system — updates Starship palette in-place
# Called as post_hook from matugen config

STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"
COLORS_FILE="$HOME/.config/starship/colors.toml"

if [[ ! -f "$COLORS_FILE" ]]; then
    exit 0
fi

# Extract the palette block from colors.toml
PALETTE_CONTENT=$(cat "$COLORS_FILE")

# Remove existing [palettes.matugen] block from starship.toml
# Find the line number of [palettes.matugen] and remove everything from there to EOF
LINE_NUM=$(grep -n '^\[palettes\.matugen\]' "$STARSHIP_CONFIG" | head -1 | cut -d: -f1)

if [[ -n "$LINE_NUM" ]]; then
    # Keep everything before the palette block
    head -n $((LINE_NUM - 1)) "$STARSHIP_CONFIG" > "${STARSHIP_CONFIG}.tmp"
    # Append the new palette
    echo "" >> "${STARSHIP_CONFIG}.tmp"
    cat "$COLORS_FILE" >> "${STARSHIP_CONFIG}.tmp"
    echo "" >> "${STARSHIP_CONFIG}.tmp"
    mv "${STARSHIP_CONFIG}.tmp" "$STARSHIP_CONFIG"
fi
