-- Generated by wallust — Hyprland colors

hl.config({
    general = {
        col = {
            active_border   = {
                colors = {
                    "rgb(9E7146)",
                    "rgb(DFC892)",
                },
                angle = 45
            },
            inactive_border = "rgb(A19986)",
        },
    },
    decoration = {
        shadow = {
            color = 0xee0B0000,
        },
    },
})
