# ╔══════════════════════════════════════╗
# ║     HOLLOWSEC HYPRLOCK CONFIG        ║
# ╚══════════════════════════════════════╝

# Matugen Material You Renk Paleti
source = ~/.config/hypr/hyprlock-colors.conf

background {
    monitor =
    path = /usr/share/sddm/themes/sugar-dark/Background.jpg

    blur_passes = 3
    blur_size = 5
    noise = 0.0117
    contrast = 0.9000
    brightness = 0.7500
    vibrancy = 0.1800
    vibrancy_darkness = 0.0
}

# ── SAAT ────────────────────────────────
label {
    monitor =
    text = $TIME
    color = rgba(224, 228, 219, 0.95)
    font_size = 88
    font_family = JetBrainsMono Nerd Font Bold
    shadow_passes = 1
    shadow_size = 4
    shadow_color = rgba(0, 0, 0, 0.4)
    shadow_boost = 1.2
    position = 0, 190
    halign = center
    valign = center
}

# ── AYRAÇ ───────────────────────────────
label {
    monitor =
    text =  ──────────────────── 
    color = rgba(156, 212, 159, 0.25)
    font_size = 10
    font_family = JetBrainsMono Nerd Font
    position = 0, 115
    halign = center
    valign = center
}

# ── TARİH ───────────────────────────────
label {
    monitor =
    text = cmd[update:43200000] echo "$(date +"%A, %d %B")"
    color = rgba(156, 212, 159, 0.85)
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 0, 90
    halign = center
    valign = center
}

# ── KULLANICI ETIKETI ────────────────────
label {
    monitor =
    text =   $USER
    color = rgba(156, 212, 159, 0.40)
    font_size = 12
    font_family = JetBrainsMono Nerd Font
    position = 0, -10
    halign = center
    valign = center
}

# ── ŞİFRE GİRİŞ KUTUSU ──────────────────
input-field {
    monitor =
    size = 280, 56
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.22
    dots_center = true
    dots_rounding = -1    # daire noktalar

    # Pasif durum
    outer_color = rgba(156, 212, 159, 0.30)
    inner_color = rgba(12, 18, 12, 0.90)
    font_color = rgba(224, 228, 219, 0.90)

    # Aktif / odak
    check_color = rgba(156, 212, 159, 1.0)
    fail_color = rgba(220, 80, 80, 0.85)
    fail_transition = 300

    fade_on_empty = true
    fade_timeout = 2000
    placeholder_text = <span foreground="##9cd49f" font_size="13" alpha="60%">  Node Locked...</span>
    hide_input = false
    rounding = 16

    shadow_passes = 2
    shadow_size = 8
    shadow_color = rgba(0, 0, 0, 0.50)
    shadow_boost = 0.8

    position = 0, -65
    halign = center
    valign = center
}

# ── ALT BİLGİ ───────────────────────────
label {
    monitor =
    text = HOLLOWSEC
    color = rgba(156, 212, 159, 0.12)
    font_size = 9
    font_family = JetBrainsMono Nerd Font
    position = 0, -160
    halign = center
    valign = center
}