listener {
    type = lock
    on-timeout = loginctl lock-session # sistem boşta kaldığında sinyali fırlatır
}

# İşte systemd'den gelen o gizemli sinyali yakalayan kısım:
listener {
    type = lock
    listener = hyprlock # Sinyal geldiği an hyprlock'u çalıştır!
}
