-- Generated by matugen — do not edit manually
-- Material You renk paleti - Hyprland border renkleri

hl.config({
    general = {
        col = {
            active_border   = {
                colors = {
                    "rgb({{colors.primary.default.hex_stripped}})",
                    "rgb({{colors.tertiary.default.hex_stripped}})",
                },
                angle = 45
            },
            inactive_border = "rgb({{colors.surface_container_highest.default.hex_stripped}})",
        },
    },
    decoration = {
        shadow = {
            color = 0xee{{colors.shadow.default.hex_stripped}},
        },
    },
})

-- Renk değişkenleri (diğer kurallar için referans)
-- primary:            {{colors.primary.default.hex}}
-- on_primary:         {{colors.on_primary.default.hex}}
-- secondary:          {{colors.secondary.default.hex}}
-- tertiary:           {{colors.tertiary.default.hex}}
-- surface:            {{colors.surface.default.hex}}
-- surface_container:  {{colors.surface_container.default.hex}}
-- on_surface:         {{colors.on_surface.default.hex}}
-- error:              {{colors.error.default.hex}}
