#!/bin/bash
# Generated by matugen — Zsh/Terminal color variables
# Source this from .zshrc

# Matugen Material You Colors
export MATUGEN_PRIMARY="{{colors.primary.default.hex}}"
export MATUGEN_ON_PRIMARY="{{colors.on_primary.default.hex}}"
export MATUGEN_SECONDARY="{{colors.secondary.default.hex}}"
export MATUGEN_TERTIARY="{{colors.tertiary.default.hex}}"
export MATUGEN_SURFACE="{{colors.surface.default.hex}}"
export MATUGEN_ON_SURFACE="{{colors.on_surface.default.hex}}"
export MATUGEN_OUTLINE="{{colors.outline.default.hex}}"
export MATUGEN_ERROR="{{colors.error.default.hex}}"
export MATUGEN_PRIMARY_CONTAINER="{{colors.primary_container.default.hex}}"
export MATUGEN_SURFACE_CONTAINER="{{colors.surface_container.default.hex}}"

# Zsh Plugin Renkleri
export MATUGEN_ZSH_AUTOSUGGEST="{{colors.outline_variant.default.hex}}"
export MATUGEN_ZSH_NUMBER="{{colors.tertiary.default.hex}}"
export MATUGEN_ZSH_OPTION="{{colors.secondary.default.hex}}"
export MATUGEN_ZSH_BRACKET="{{colors.tertiary_fixed_dim.default.hex}}"
